In [218]:
import numpy as np
import random as rnd
import itertools as itt
import math

GENERATIVE_MATRIX_LIST = [[0 for i in range(24)] for j in range(12)]
for i in range(12):
    for j in range(12):
        if i == j:
            GENERATIVE_MATRIX_LIST[i][j] = 1

GENERATIVE_MATRIX_LIST[0][12:] = [1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1]
GENERATIVE_MATRIX_LIST[1][12:] = [0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0]
GENERATIVE_MATRIX_LIST[2][12:] = [0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1]
GENERATIVE_MATRIX_LIST[3][12:] = [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0]
GENERATIVE_MATRIX_LIST[4][12:] = [1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1]
GENERATIVE_MATRIX_LIST[5][12:] = [1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0]
GENERATIVE_MATRIX_LIST[6][12:] = [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1]
GENERATIVE_MATRIX_LIST[7][12:] = [1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0]
GENERATIVE_MATRIX_LIST[8][12:] = [0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1]
GENERATIVE_MATRIX_LIST[9][12:] = [0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0]
GENERATIVE_MATRIX_LIST[10][12:] = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1]
GENERATIVE_MATRIX_LIST[11][12:] = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1]
GENERATIVE_MATRIX_GOLAY_24_12_8_2 = np.matrix(GENERATIVE_MATRIX_LIST)

In [219]:
P = np.compress(
    [0 for i in range(12)] + [1 for i in range(12)],
    GENERATIVE_MATRIX_GOLAY_24_12_8_2,
    axis=1,
)

In [220]:
P

matrix([[1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1],
        [0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1],
        [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0],
        [1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1],
        [1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0],
        [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1],
        [1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0],
        [0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1],
        [0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1]])

In [221]:
P.getT()

matrix([[1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1],
        [0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1],
        [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0],
        [1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1],
        [1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0],
        [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1],
        [1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0],
        [0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1],
        [0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1]])

In [222]:
I = P = np.compress(
    [1 for i in range(12)] + [0 for i in range(12)],
    GENERATIVE_MATRIX_GOLAY_24_12_8_2,
    axis=1,
)

In [223]:
I

matrix([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [224]:
P + I

matrix([[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]])

In [225]:
PARITY_CHECK_MATRIX_GOLAY_24_12_8_2 = np.matrix(
    [
        [1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    ]
)

In [226]:
msg = [rnd.randrange(0, 2) for i in range(12)]

In [227]:
MESSAGE = np.matrix(msg)

In [228]:
ENCODED_MESSAGE = np.matmul(MESSAGE, GENERATIVE_MATRIX_GOLAY_24_12_8_2)
ENCODED_MESSAGE

matrix([[0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 4, 4, 3, 2, 2, 1, 1, 2, 2,
         3, 2, 2]])

In [229]:
ENCODED_MESSAGE = np.apply_along_axis(lambda x: x % 2, 1, ENCODED_MESSAGE)
ENCODED_MESSAGE

matrix([[0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
         1, 0, 0]], dtype=int32)

In [230]:
np.apply_along_axis(
    lambda x: x % 2,
    1,
    np.matmul(ENCODED_MESSAGE, PARITY_CHECK_MATRIX_GOLAY_24_12_8_2.getT()),
)

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [231]:
ENCODED_MESSAGE[0, 3] = ENCODED_MESSAGE[0, 3] ^ 1
ENCODED_MESSAGE[0, 2] = ENCODED_MESSAGE[0, 2] ^ 1
ENCODED_MESSAGE[0, 15] = ENCODED_MESSAGE[0, 15] ^ 1
ENCODED_MESSAGE

matrix([[0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
         1, 0, 0]], dtype=int32)

In [232]:
tuple(
    np.array(
        np.apply_along_axis(
            lambda x: x % 2,
            1,
            np.matmul(ENCODED_MESSAGE, PARITY_CHECK_MATRIX_GOLAY_24_12_8_2.getT()),
        )
    )[0]
)

(1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1)

In [233]:
def return_syndrome_hash_map(PARITY_CHECK_MATRIX, distance):
    SYNDROME_HASH_MAP = {}
    correctionInterval = math.floor((distance - 1) / 2)
    codedWordLength = (np.array(PARITY_CHECK_MATRIX).shape)[1]
    PARITY_CHECK_MATRIX_TRANSPOSE = PARITY_CHECK_MATRIX.getT()
    TEST_MESSAGE = [0 for i in range(codedWordLength)]
    INDEXES = [i for i in range(codedWordLength)]
    for bitflipsNum in range(correctionInterval + 1):
        combinations = list(itt.combinations(INDEXES, bitflipsNum))
        for bitflipScenario in range(math.comb(codedWordLength, bitflipsNum)):
            for i in combinations[bitflipScenario]:
                TEST_MESSAGE[i] = 1
            syndromeTuple = tuple(
                np.array(
                    np.apply_along_axis(
                        lambda x: x % 2,
                        1,
                        np.matmul(TEST_MESSAGE, PARITY_CHECK_MATRIX_TRANSPOSE),
                    )
                )[0]
            )
            SYNDROME_HASH_MAP.setdefault(syndromeTuple, combinations[bitflipScenario])
            TEST_MESSAGE = [0 for i in range(codedWordLength)]
    return SYNDROME_HASH_MAP


GOLAY_24_12_8_2_SYNDROME_HASH_MAP = return_syndrome_hash_map(
    PARITY_CHECK_MATRIX_GOLAY_24_12_8_2, 8
)

In [234]:
GOLAY_24_12_8_2_SYNDROME_HASH_MAP

{(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): (),
 (1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1): (0,),
 (0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0): (1,),
 (0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1): (2,),
 (1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0): (3,),
 (1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1): (4,),
 (1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0): (5,),
 (1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1): (6,),
 (1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0): (7,),
 (0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1): (8,),
 (0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0): (9,),
 (0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1): (10,),
 (1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1): (11,),
 (1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): (12,),
 (0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0): (13,),
 (0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0): (14,),
 (0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0): (15,),
 (0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0): (16,),
 (0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0): (17,),
 (0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0): (18,),
 (0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0): (19,),
 (0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0): (20,),
 

In [235]:
def return_syndrome_tuple(SYNDROME_HASH_MAP, PARITY_CHECK_MATRIX, ENCODED_MESSAGE):
    return SYNDROME_HASH_MAP[
        tuple(
            np.array(
                np.apply_along_axis(
                    lambda x: x % 2,
                    1,
                    np.matmul(ENCODED_MESSAGE, PARITY_CHECK_MATRIX.getT()),
                )
            )[0]
        )
    ]

def encode_msg(GENERATIVE_MATRIX,MSG):
    MSG = np.matrix(MSG)
    MSG = np.matmul(MSG,GENERATIVE_MATRIX)
    return np.apply_along_axis(lambda x: x % 2, 1, MSG)

In [236]:
return_syndrome_tuple(GOLAY_24_12_8_2_SYNDROME_HASH_MAP,PARITY_CHECK_MATRIX_GOLAY_24_12_8_2,ENCODED_MESSAGE)

(2, 3, 15)

In [237]:
GENERATIVE_MATRIX_HAMMING_7_4_3_2 = np.matrix([
    [1,0,0,0,1,1,0],
    [0,1,0,0,1,0,1],
    [0,0,1,0,0,1,1],
    [0,0,0,1,1,1,1],
])

PARITY_CHECK_MATRIX_HAMMING_7_4_3_2 = np.matrix([
    [1,1,0,1,1,0,0],
    [1,0,1,1,0,1,0],
    [0,1,1,1,0,0,1],
])

HAMMING_7_4_3_2_SYNDROME_HASH_MAP = return_syndrome_hash_map(PARITY_CHECK_MATRIX_HAMMING_7_4_3_2,3)
HAMMING_7_4_3_2_SYNDROME_HASH_MAP

{(0, 0, 0): (),
 (1, 1, 0): (0,),
 (1, 0, 1): (1,),
 (0, 1, 1): (2,),
 (1, 1, 1): (3,),
 (1, 0, 0): (4,),
 (0, 1, 0): (5,),
 (0, 0, 1): (6,)}

In [238]:
MSG_H = [rnd.randrange(0, 2) for i in range(4)]

ENCODED_MSG_H = encode_msg(GENERATIVE_MATRIX_HAMMING_7_4_3_2,MSG_H)
ENCODED_MSG_H[0,0] = ENCODED_MSG_H[0,0]^1

In [239]:
return_syndrome_tuple(HAMMING_7_4_3_2_SYNDROME_HASH_MAP,PARITY_CHECK_MATRIX_HAMMING_7_4_3_2,ENCODED_MSG_H)

(0,)

In [258]:
def ENCODE_CHANNEL_MESSAGE(msg):
    blocks = [b1, b2, b3, b4, b5, b6, b7, b8, b9] = [
        msg[:12],
        msg[12:24],
        msg[24:36],
        msg[36:48],
        msg[48:60],
        msg[60:72],
        msg[72:84],
        msg[84:96],
        msg[96:],
    ]
    encodedMSG = []
    for block in blocks[:8]:
       encodedBlockMSG = encode_msg(GENERATIVE_MATRIX_GOLAY_24_12_8_2,block)
       encodedBlockMSG = list(np.array(encodedBlockMSG)[0])
       encodedMSG.extend(encodedBlockMSG)
    encodedBlockMSG = encode_msg(GENERATIVE_MATRIX_HAMMING_7_4_3_2,b9)
    encodedBlockMSG = list(np.array(encodedBlockMSG)[0])
    encodedMSG.extend(encodedBlockMSG)
    return encodedMSG
    

In [259]:
msgRnd = [rnd.randrange(0, 2) for i in range(100)]
ENCODED_MSG_RND = ENCODE_CHANNEL_MESSAGE(msgRnd)
print(ENCODED_MSG_RND,len(ENCODED_MSG_RND))

[1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0] 199


In [272]:
# Postavljeno na ispravljanje
def DECODE_CHANNEL_MESSAGE(encodedMsg):
    blocks = [b1, b2, b3, b4, b5, b6, b7, b8, b9] = [
        encodedMsg[:24],
        encodedMsg[24:48],
        encodedMsg[48:72],
        encodedMsg[72:96],
        encodedMsg[96:120],
        encodedMsg[120:144],
        encodedMsg[144:168],
        encodedMsg[168:192],
        encodedMsg[192:],
    ]
    for offset, block in enumerate(blocks[:8]):
        synTuple = return_syndrome_tuple(
            GOLAY_24_12_8_2_SYNDROME_HASH_MAP,
            PARITY_CHECK_MATRIX_GOLAY_24_12_8_2,
            np.matrix(block),
        )
        for index in synTuple:
            encodedMsg[offset * 24 + index] = encodedMsg[offset * 24 + index] ^ 1
    synTuple = return_syndrome_tuple(
        HAMMING_7_4_3_2_SYNDROME_HASH_MAP,
        PARITY_CHECK_MATRIX_HAMMING_7_4_3_2,
        np.matrix(b9),
    )
    for index in synTuple:
        encodedMsg[192+ index] = encodedMsg[192+ index] ^ 1
    return encodedMsg

In [ ]:
#GREŠKA - PRIMJER
ENCODED_MSG_RND[2] = ENCODED_MSG_RND[2]^1
print(ENCODED_MSG_RND)
DECODED_MESSAGE_RND = DECODE_CHANNEL_MESSAGE(ENCODED_MSG_RND)
print(DECODED_MESSAGE_RND)
print(len(DECODED_MESSAGE_RND))

[1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,